build:       
  image: rust:1.62-buster
  stage: build
  timeout: 30 minutes
  tags:
    - gfw_free
  script:
    - apt update && apt install -y curl 
    - cat /etc/*release
    - lscpu
    - cd remote_shell_executor && cargo b && cargo clippy
    - bash scripts/run_test.sh