name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  run:
    runs-on: ubuntu-20.04
    container:
      image: rust:1.62-buster
    steps:
      - uses: actions/checkout@v2

      - name: Prepare system
        run: |
          apt-get update && apt-get install -y curl procps 
          lscpu
          free -h
          df -h

      - name: Build
        shell: bash
        run: |
          cd remote_shell_executor
          cargo b

      - name: Test
        shell: bash
        run: |
          bash scripts/run_test.sh